### register
POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "bryan",
    "password": "bryan123",
    "email": "diazpachecobrayan@gmail.com"
}

### login
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{   
    "password": "bryan123",
    "email": "diazpachecobrayan@gmail.com"
}

### verificar el email del usuario
GET http://localhost:8080/api/email/verify?token=dHcn43ylb-dCfmD5jgGaRLZLy2Lk4XKpSZKWfYek1CQ HTTP/1.1

### rotar los refresh token
POST http://localhost:8080/api/auth/refresh/rotate HTTP/1.1
Content-Type: application/json
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9VU0VSIl0sImF1dGhTdGF0dXMiOiJBQ1RJVkUiLCJpc3MiOiJCUjdGT1JMSUZFLmNvbSIsImV4cCI6MTc3NTcxNDM4OCwidXNlcklkIjoiMTEyYTUxMjctZjEyMC00Yzc3LWJjMTgtY2I1Njc0NzdmYmRmIiwiaWF0IjoxNzc1NDk4Mzg4LCJqdGkiOiJlMTg3MzUxOC0yODhjLTRjMzQtODg0ZC0zN2Q3ZjJjZjFkOTIifQ.XmWc7qSHGbBKFeODYY9jss2xqAfNc0Ey1P10-J2YK7pVvmXNVVXZgIo5MgX3i6E4Njp1c78A2rhWvRC50V2wz2pejm0FYzWEHMbe5xRF_M0uOWE-KwFRKiwoG2qqyH4Hv4IFTYrWTzkwzDf1P2L-8LRTXzAgZCC2hAq1Bf_kO941BrYNv8A4UaarKe25hd55NBj2vmhJgBTm47KJaazewx0e4KG-nKxO_NZ6qm2LmTtFdggO-Y2pck3Mh1dlr4PmXDOxxul5oPw-WG7AIyrfOwolOOfMw_Qh3u-jbR9-R5mQRddDImJrkDrqwxHsofzKYa02GZXzFnDsjkSCeCtkEQ
Cookie:refresh_token=LeMDBaKYMeTxk7nFNaugtqduJ4uRUIYHvNOBu97Jf6Y; Max-Age=2592000; Expires=Wed, 06 May 2026 17:59:48 GMT;

### pedir los access token
POST http://localhost:8080/api/auth/refresh HTTP/1.1
Content-Type: application/json
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9VU0VSIl0sImF1dGhTdGF0dXMiOiJBQ1RJVkUiLCJpc3MiOiJCUjdGT1JMSUZFLmNvbSIsImV4cCI6MTc3NTcxNDM4OCwidXNlcklkIjoiMTEyYTUxMjctZjEyMC00Yzc3LWJjMTgtY2I1Njc0NzdmYmRmIiwiaWF0IjoxNzc1NDk4Mzg4LCJqdGkiOiJlMTg3MzUxOC0yODhjLTRjMzQtODg0ZC0zN2Q3ZjJjZjFkOTIifQ.XmWc7qSHGbBKFeODYY9jss2xqAfNc0Ey1P10-J2YK7pVvmXNVVXZgIo5MgX3i6E4Njp1c78A2rhWvRC50V2wz2pejm0FYzWEHMbe5xRF_M0uOWE-KwFRKiwoG2qqyH4Hv4IFTYrWTzkwzDf1P2L-8LRTXzAgZCC2hAq1Bf_kO941BrYNv8A4UaarKe25hd55NBj2vmhJgBTm47KJaazewx0e4KG-nKxO_NZ6qm2LmTtFdggO-Y2pck3Mh1dlr4PmXDOxxul5oPw-WG7AIyrfOwolOOfMw_Qh3u-jbR9-R5mQRddDImJrkDrqwxHsofzKYa02GZXzFnDsjkSCeCtkEQ
Cookie:refresh_token=HfpkmdAslc6Dog3_ASzLBIfcGenGrUaWZbJuszeIhxs; Max-Age=2592000; Expires=Wed, 06 May 2026 17:59:48 GMT;  


### logout 
POST http://localhost:8080/api/auth/logout HTTP/1.1
Content-Type: application/json
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9VU0VSIl0sImF1dGhTdGF0dXMiOiJBQ1RJVkUiLCJpc3MiOiJCUjdGT1JMSUZFLmNvbSIsImV4cCI6MTc3NTcxNDM4OCwidXNlcklkIjoiMTEyYTUxMjctZjEyMC00Yzc3LWJjMTgtY2I1Njc0NzdmYmRmIiwiaWF0IjoxNzc1NDk4Mzg4LCJqdGkiOiJlMTg3MzUxOC0yODhjLTRjMzQtODg0ZC0zN2Q3ZjJjZjFkOTIifQ.XmWc7qSHGbBKFeODYY9jss2xqAfNc0Ey1P10-J2YK7pVvmXNVVXZgIo5MgX3i6E4Njp1c78A2rhWvRC50V2wz2pejm0FYzWEHMbe5xRF_M0uOWE-KwFRKiwoG2qqyH4Hv4IFTYrWTzkwzDf1P2L-8LRTXzAgZCC2hAq1Bf_kO941BrYNv8A4UaarKe25hd55NBj2vmhJgBTm47KJaazewx0e4KG-nKxO_NZ6qm2LmTtFdggO-Y2pck3Mh1dlr4PmXDOxxul5oPw-WG7AIyrfOwolOOfMw_Qh3u-jbR9-R5mQRddDImJrkDrqwxHsofzKYa02GZXzFnDsjkSCeCtkEQ
Cookie:refresh_token=LeMDBaKYMeTxk7nFNaugtqduJ4uRUIYHvNOBu97Jf6Y; Max-Age=2592000; Expires=Wed, 06 May 2026 17:59:48 GMT;

### /me
GET http://localhost:8080/api/auth/me HTTP/1.1
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9VU0VSIl0sImF1dGhTdGF0dXMiOiJBQ1RJVkUiLCJpc3MiOiJCUjdGT1JMSUZFLmNvbSIsImV4cCI6MTc3NjQ4Nzc4OCwidXNlcklkIjoiYmJkMGZiYWYtMjMxOS00ZDM3LThkY2EtZWRmNDY4NDZiYWNiIiwiaWF0IjoxNzc2MjcxNzg4LCJqdGkiOiIxNjJhZmVlMC01Mjk4LTRlYzAtYTE4Mi1iMjBjZDQ1N2YxZjYifQ.Rz-RfAt8y5Viu2Pq1jQU9Y16o7jv6Zt22O-qpcEwBniKr3NuKI-StvjbBI5AE0GFtAN3YxuWA0GWSbSKmPS1yaLHQoSV_4vg9PU_eFDFqsI_HtvYLX9zCh_7IaE-WDshhrbNoUfKcx0gSp1hwsOZIMEl08UmHz43ReGVh49N1ojL4kfZc1Rc2q67i4t01G1axJR_9EF_Q-ssLsOAYHwFJtGJaV9pcEWnK82zDsZLzrRluQPU0fjlYo6Wr91a5qQQPkxuxY_Qy3cZDnZa-jR__-6Q8DK_3XYkl9aJgqE-3gvshAFcEp9qgTSEgETq-7g_2rTE197khtVU0hjYRNI4aA

