### register
POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "bryan",
    "password": "bryan123",
    "email": "diazpachecobrayan@gmail.com"
}

### login
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{   
    "password": "bryan123",
    "email": "diazpachecobrayan@gmail.com"
}

### verificar el email del usuario
GET http://localhost:8080/api/email/verify?token=WiFH55rH6PboGcZUnyJZ1LX18DAN9j_W2dgCsL2opaA HTTP/1.1

### refresh token
POST http://localhost:8080/api/auth/refresh HTTP/1.1
Content-Type: application/json
Cookie:refresh_token=0KuqmdszI9GdZ8i3XYrtqQZtV0NJ2lrNVoCvFNayR4g; Path=/api/auth; HttpOnly; Expires=Tue, 07 Apr 2026 01:11:37 GMT;


### logout 
POST http://localhost:8080/api/auth/logout HTTP/1.1
Content-Type: application/json
Cookie:refresh_token=bPJKT9qrHTRkYpCr8fEHZM_x6zWLsc56lt7bXtvNWVU; Path=/api/auth; HttpOnly; Expires=Tue, 07 Apr 2026 01:08:14 GMT;