### register
POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "bryan",
    "password": "bryan123",
    "email": "diazpachecobrayan@gmail.com"
}

### login
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{   
    "password": "bryan123",
    "email": "diazpachecobrayan@gmail.com"
}

### verificar el email del usuario
GET http://localhost:8080/api/email/verify?token=BWDlgCXF3FymUcKq4t3cLNMfsbYAc5aCcI_tUbvqjB8 HTTP/1.1

### rotar los refresh token
POST http://localhost:8080/api/auth/refresh/rotate HTTP/1.1
Content-Type: application/json
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9VU0VSIl0sImF1dGhTdGF0dXMiOiJBQ1RJVkUiLCJpc3MiOiJCUjdGT1JMSUZFLmNvbSIsImV4cCI6MTc3NTcxNDM4OCwidXNlcklkIjoiMTEyYTUxMjctZjEyMC00Yzc3LWJjMTgtY2I1Njc0NzdmYmRmIiwiaWF0IjoxNzc1NDk4Mzg4LCJqdGkiOiJlMTg3MzUxOC0yODhjLTRjMzQtODg0ZC0zN2Q3ZjJjZjFkOTIifQ.XmWc7qSHGbBKFeODYY9jss2xqAfNc0Ey1P10-J2YK7pVvmXNVVXZgIo5MgX3i6E4Njp1c78A2rhWvRC50V2wz2pejm0FYzWEHMbe5xRF_M0uOWE-KwFRKiwoG2qqyH4Hv4IFTYrWTzkwzDf1P2L-8LRTXzAgZCC2hAq1Bf_kO941BrYNv8A4UaarKe25hd55NBj2vmhJgBTm47KJaazewx0e4KG-nKxO_NZ6qm2LmTtFdggO-Y2pck3Mh1dlr4PmXDOxxul5oPw-WG7AIyrfOwolOOfMw_Qh3u-jbR9-R5mQRddDImJrkDrqwxHsofzKYa02GZXzFnDsjkSCeCtkEQ
Cookie:refresh_token=LeMDBaKYMeTxk7nFNaugtqduJ4uRUIYHvNOBu97Jf6Y; Max-Age=2592000; Expires=Wed, 06 May 2026 17:59:48 GMT;

### pedir los access token
POST http://localhost:8080/api/auth/refresh HTTP/1.1
Content-Type: application/json
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9VU0VSIl0sImF1dGhTdGF0dXMiOiJBQ1RJVkUiLCJpc3MiOiJCUjdGT1JMSUZFLmNvbSIsImV4cCI6MTc3NTcxNDM4OCwidXNlcklkIjoiMTEyYTUxMjctZjEyMC00Yzc3LWJjMTgtY2I1Njc0NzdmYmRmIiwiaWF0IjoxNzc1NDk4Mzg4LCJqdGkiOiJlMTg3MzUxOC0yODhjLTRjMzQtODg0ZC0zN2Q3ZjJjZjFkOTIifQ.XmWc7qSHGbBKFeODYY9jss2xqAfNc0Ey1P10-J2YK7pVvmXNVVXZgIo5MgX3i6E4Njp1c78A2rhWvRC50V2wz2pejm0FYzWEHMbe5xRF_M0uOWE-KwFRKiwoG2qqyH4Hv4IFTYrWTzkwzDf1P2L-8LRTXzAgZCC2hAq1Bf_kO941BrYNv8A4UaarKe25hd55NBj2vmhJgBTm47KJaazewx0e4KG-nKxO_NZ6qm2LmTtFdggO-Y2pck3Mh1dlr4PmXDOxxul5oPw-WG7AIyrfOwolOOfMw_Qh3u-jbR9-R5mQRddDImJrkDrqwxHsofzKYa02GZXzFnDsjkSCeCtkEQ
Cookie:refresh_token=HfpkmdAslc6Dog3_ASzLBIfcGenGrUaWZbJuszeIhxs; Max-Age=2592000; Expires=Wed, 06 May 2026 17:59:48 GMT;  


### logout 
POST http://localhost:8080/api/auth/logout HTTP/1.1
Content-Type: application/json
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9VU0VSIl0sImF1dGhTdGF0dXMiOiJBQ1RJVkUiLCJpc3MiOiJCUjdGT1JMSUZFLmNvbSIsImV4cCI6MTc3NTcxNDM4OCwidXNlcklkIjoiMTEyYTUxMjctZjEyMC00Yzc3LWJjMTgtY2I1Njc0NzdmYmRmIiwiaWF0IjoxNzc1NDk4Mzg4LCJqdGkiOiJlMTg3MzUxOC0yODhjLTRjMzQtODg0ZC0zN2Q3ZjJjZjFkOTIifQ.XmWc7qSHGbBKFeODYY9jss2xqAfNc0Ey1P10-J2YK7pVvmXNVVXZgIo5MgX3i6E4Njp1c78A2rhWvRC50V2wz2pejm0FYzWEHMbe5xRF_M0uOWE-KwFRKiwoG2qqyH4Hv4IFTYrWTzkwzDf1P2L-8LRTXzAgZCC2hAq1Bf_kO941BrYNv8A4UaarKe25hd55NBj2vmhJgBTm47KJaazewx0e4KG-nKxO_NZ6qm2LmTtFdggO-Y2pck3Mh1dlr4PmXDOxxul5oPw-WG7AIyrfOwolOOfMw_Qh3u-jbR9-R5mQRddDImJrkDrqwxHsofzKYa02GZXzFnDsjkSCeCtkEQ
Cookie:refresh_token=LeMDBaKYMeTxk7nFNaugtqduJ4uRUIYHvNOBu97Jf6Y; Max-Age=2592000; Expires=Wed, 06 May 2026 17:59:48 GMT;

### /me
GET http://localhost:8080/api/auth/me HTTP/1.1
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9BRE1JTiJdLCJhdXRoU3RhdHVzIjoiQUNUSVZFIiwiaXNzIjoiQlI3Rk9STElGRS5jb20iLCJleHAiOjE3NzYzMTA2MjYsInVzZXJJZCI6IjNjNWI4MzFjLTlkOWMtNGRjMy05NzhiLWU3NDAxYWQwMDE1YSIsImlhdCI6MTc3NjA5NDYyNiwianRpIjoiZjcwOWQyOGUtMTQzOS00Njk5LTkwMzQtMDgyYjI5YzU4MmQ1In0.GUmWo8wEcBg3fci15E414snflDVOwB2rkEfHg7gqCRzPIVJNAoLPkzQdz2iyzzw5qWozPasLaBcVovO49TeMbFnbfZfNtjpGWsqf2k05FKGWP75zlUMephCRZY_yESj5ByhgURYpnjLUZLOw-gfE98oKnNCA2WvUd9p0UBqhlS0En5ZrJ07qm92TsUgfQVaoL_PAawdAuC5cKROibp_exctp-jOjiGqFJZtapcniUyKobt99KeGFn52_jeuzdx8Zkygttno0rqJ8aloVdaIMkdtz_H9f6o6e7uY4UPxbFjqimn9iShp2nPY9mRB_gAZB9k8H6gyhbqj5GGKmmDuG1w
