### crear un listing

POST http://localhost:8080/api/listing HTTP/1.1
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9BRE1JTiJdLCJhdXRoU3RhdHVzIjoiQUNUSVZFIiwiaXNzIjoiQlI3Rk9STElGRS5jb20iLCJleHAiOjE3NzYzMTA2MjYsInVzZXJJZCI6IjNjNWI4MzFjLTlkOWMtNGRjMy05NzhiLWU3NDAxYWQwMDE1YSIsImlhdCI6MTc3NjA5NDYyNiwianRpIjoiZjcwOWQyOGUtMTQzOS00Njk5LTkwMzQtMDgyYjI5YzU4MmQ1In0.GUmWo8wEcBg3fci15E414snflDVOwB2rkEfHg7gqCRzPIVJNAoLPkzQdz2iyzzw5qWozPasLaBcVovO49TeMbFnbfZfNtjpGWsqf2k05FKGWP75zlUMephCRZY_yESj5ByhgURYpnjLUZLOw-gfE98oKnNCA2WvUd9p0UBqhlS0En5ZrJ07qm92TsUgfQVaoL_PAawdAuC5cKROibp_exctp-jOjiGqFJZtapcniUyKobt99KeGFn52_jeuzdx8Zkygttno0rqJ8aloVdaIMkdtz_H9f6o6e7uY4UPxbFjqimn9iShp2nPY9mRB_gAZB9k8H6gyhbqj5GGKmmDuG1w
Cookie:refresh_token=wIoU0p01hvlv5e589iCvhspmubVwlUZ7M9SIHBh28ac; Max-Age=2592000; Expires=Wed, 13 May 2026 15:37:06 GMT;
Content-Type: application/json


{
  "product": {
    "name": "Google Pixel 8",
    "shortDescription": "android puro",
    "longDescription": "cámara increíble",
    "model": "Pixel 8",
    "sku": "GP8-007"
  },
  "price": 950,
  "currency": "USD"
}


### obtener un listing por ID
POST http://localhost:8080/api/listing/385076c6-d9d6-4553-b04f-35711991c0c8 HTTP/1.1
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9VU0VSIl0sImF1dGhTdGF0dXMiOiJBQ1RJVkUiLCJpc3MiOiJCUjdGT1JMSUZFLmNvbSIsImV4cCI6MTc3NTcwMjY2NCwidXNlcklkIjoiMTEyYTUxMjctZjEyMC00Yzc3LWJjMTgtY2I1Njc0NzdmYmRmIiwiaWF0IjoxNzc1NDg2NjY0LCJqdGkiOiIxNjQyMzMxZi0xZDRlLTQ5YjctYWQ1MC03YmVlNzY0NjVjZTAifQ.m7C95Ffhy-u1VBRct4hZVFz18NS9jxDutnapQc8QGG0HyXrvpxT4z50OzOdSSu4D6FR0NygIIYKYhdCnqH0pikhjHvReAYOjYhfJzOvKCDsHPNT6O6t-spOdNR6ivBY-Rt9PR9ROc4Tw8qUBbKNsMZD_rpaqIZ8xsXSzjHUWo2a-ilrFS6WjYxe6m0y_2K2snplAbYv2toiPAShg8LsDfnP_RfrVZfk5UZp8OorFoZgrNP1uHNni4I4UCP0loG_txKdB1GLA8Gh7L4J0NzioUSZYKmHudNuVmjA4msKlh985MOyddqkYNDUaWitEh3iCN8XUTVlsrGjZ11u99245ZQ
Cookie:refresh_token=PfxdzcuQVv0gvBdNQkGZx0b1gyQDKhwFzaqRTHTfaWI; Max-Age=2592000; Expires=Wed, 06 May 2026 14:44:24 GMT;
Content-Type: application/json


### Obtener todos los listings paginados
GET http://localhost:8080/api/listing HTTP/1.1
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9BRE1JTiJdLCJhdXRoU3RhdHVzIjoiQUNUSVZFIiwiaXNzIjoiQlI3Rk9STElGRS5jb20iLCJleHAiOjE3NzYzMTA2MjYsInVzZXJJZCI6IjNjNWI4MzFjLTlkOWMtNGRjMy05NzhiLWU3NDAxYWQwMDE1YSIsImlhdCI6MTc3NjA5NDYyNiwianRpIjoiZjcwOWQyOGUtMTQzOS00Njk5LTkwMzQtMDgyYjI5YzU4MmQ1In0.GUmWo8wEcBg3fci15E414snflDVOwB2rkEfHg7gqCRzPIVJNAoLPkzQdz2iyzzw5qWozPasLaBcVovO49TeMbFnbfZfNtjpGWsqf2k05FKGWP75zlUMephCRZY_yESj5ByhgURYpnjLUZLOw-gfE98oKnNCA2WvUd9p0UBqhlS0En5ZrJ07qm92TsUgfQVaoL_PAawdAuC5cKROibp_exctp-jOjiGqFJZtapcniUyKobt99KeGFn52_jeuzdx8Zkygttno0rqJ8aloVdaIMkdtz_H9f6o6e7uY4UPxbFjqimn9iShp2nPY9mRB_gAZB9k8H6gyhbqj5GGKmmDuG1w
Cookie:refresh_token=wIoU0p01hvlv5e589iCvhspmubVwlUZ7M9SIHBh28ac; Max-Age=2592000; Expires=Wed, 13 May 2026 15:37:06 GMT;

### cambiar el estado de un listing
PATCH http://localhost:8080/api/listing/59e3ae4c-d3ab-4157-82f6-27cd6c0afbb3/status HTTP/1.1
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9BRE1JTiJdLCJhdXRoU3RhdHVzIjoiQUNUSVZFIiwiaXNzIjoiQlI3Rk9STElGRS5jb20iLCJleHAiOjE3NzYzMTA2MjYsInVzZXJJZCI6IjNjNWI4MzFjLTlkOWMtNGRjMy05NzhiLWU3NDAxYWQwMDE1YSIsImlhdCI6MTc3NjA5NDYyNiwianRpIjoiZjcwOWQyOGUtMTQzOS00Njk5LTkwMzQtMDgyYjI5YzU4MmQ1In0.GUmWo8wEcBg3fci15E414snflDVOwB2rkEfHg7gqCRzPIVJNAoLPkzQdz2iyzzw5qWozPasLaBcVovO49TeMbFnbfZfNtjpGWsqf2k05FKGWP75zlUMephCRZY_yESj5ByhgURYpnjLUZLOw-gfE98oKnNCA2WvUd9p0UBqhlS0En5ZrJ07qm92TsUgfQVaoL_PAawdAuC5cKROibp_exctp-jOjiGqFJZtapcniUyKobt99KeGFn52_jeuzdx8Zkygttno0rqJ8aloVdaIMkdtz_H9f6o6e7uY4UPxbFjqimn9iShp2nPY9mRB_gAZB9k8H6gyhbqj5GGKmmDuG1w
Cookie:refresh_token=wIoU0p01hvlv5e589iCvhspmubVwlUZ7M9SIHBh28ac; Max-Age=2592000; Expires=Wed, 13 May 2026 15:37:06 GMT;
Content-Type: application/json 

{
  "publicationStatus": "ACTIVE"
}