### crear un listing

POST http://localhost:8080/api/listing HTTP/1.1
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9VU0VSIl0sImF1dGhTdGF0dXMiOiJBQ1RJVkUiLCJpc3MiOiJCUjdGT1JMSUZFLmNvbSIsImV4cCI6MTc3NjQ4Nzc4OCwidXNlcklkIjoiYmJkMGZiYWYtMjMxOS00ZDM3LThkY2EtZWRmNDY4NDZiYWNiIiwiaWF0IjoxNzc2MjcxNzg4LCJqdGkiOiIxNjJhZmVlMC01Mjk4LTRlYzAtYTE4Mi1iMjBjZDQ1N2YxZjYifQ.Rz-RfAt8y5Viu2Pq1jQU9Y16o7jv6Zt22O-qpcEwBniKr3NuKI-StvjbBI5AE0GFtAN3YxuWA0GWSbSKmPS1yaLHQoSV_4vg9PU_eFDFqsI_HtvYLX9zCh_7IaE-WDshhrbNoUfKcx0gSp1hwsOZIMEl08UmHz43ReGVh49N1ojL4kfZc1Rc2q67i4t01G1axJR_9EF_Q-ssLsOAYHwFJtGJaV9pcEWnK82zDsZLzrRluQPU0fjlYo6Wr91a5qQQPkxuxY_Qy3cZDnZa-jR__-6Q8DK_3XYkl9aJgqE-3gvshAFcEp9qgTSEgETq-7g_2rTE197khtVU0hjYRNI4aA
Cookie:refresh_token=Hd0-EMRLUj7CO-rrVvLgMaBJD33rTPpt5jXW0i1R86s; Max-Age=2592000; Expires=Fri, 15 May 2026 16:49:48 GMT;
Content-Type: application/json


{
  "product": {
    "name": "Google Pixel 8",
    "shortDescription": "android puro",
    "longDescription": "cámara increíble",
    "model": "Pixel 8",
    "sku": "GP8-007"
  },
  "price": 950,
  "currency": "USD"
}


### obtener un listing por ID
POST http://localhost:8080/api/listing/884caaa4-f85a-41a7-abae-753449a87c04 HTTP/1.1
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9VU0VSIl0sImF1dGhTdGF0dXMiOiJBQ1RJVkUiLCJpc3MiOiJCUjdGT1JMSUZFLmNvbSIsImV4cCI6MTc3NjQ4Nzc4OCwidXNlcklkIjoiYmJkMGZiYWYtMjMxOS00ZDM3LThkY2EtZWRmNDY4NDZiYWNiIiwiaWF0IjoxNzc2MjcxNzg4LCJqdGkiOiIxNjJhZmVlMC01Mjk4LTRlYzAtYTE4Mi1iMjBjZDQ1N2YxZjYifQ.Rz-RfAt8y5Viu2Pq1jQU9Y16o7jv6Zt22O-qpcEwBniKr3NuKI-StvjbBI5AE0GFtAN3YxuWA0GWSbSKmPS1yaLHQoSV_4vg9PU_eFDFqsI_HtvYLX9zCh_7IaE-WDshhrbNoUfKcx0gSp1hwsOZIMEl08UmHz43ReGVh49N1ojL4kfZc1Rc2q67i4t01G1axJR_9EF_Q-ssLsOAYHwFJtGJaV9pcEWnK82zDsZLzrRluQPU0fjlYo6Wr91a5qQQPkxuxY_Qy3cZDnZa-jR__-6Q8DK_3XYkl9aJgqE-3gvshAFcEp9qgTSEgETq-7g_2rTE197khtVU0hjYRNI4aA
Cookie:refresh_token=Hd0-EMRLUj7CO-rrVvLgMaBJD33rTPpt5jXW0i1R86s; Max-Age=2592000; Expires=Fri, 15 May 2026 16:49:48 GMT;
Content-Type: application/json


### Obtener todos los listings paginados
GET http://localhost:8080/api/listing HTTP/1.1
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9VU0VSIl0sImF1dGhTdGF0dXMiOiJBQ1RJVkUiLCJpc3MiOiJCUjdGT1JMSUZFLmNvbSIsImV4cCI6MTc3NjQ4Nzc4OCwidXNlcklkIjoiYmJkMGZiYWYtMjMxOS00ZDM3LThkY2EtZWRmNDY4NDZiYWNiIiwiaWF0IjoxNzc2MjcxNzg4LCJqdGkiOiIxNjJhZmVlMC01Mjk4LTRlYzAtYTE4Mi1iMjBjZDQ1N2YxZjYifQ.Rz-RfAt8y5Viu2Pq1jQU9Y16o7jv6Zt22O-qpcEwBniKr3NuKI-StvjbBI5AE0GFtAN3YxuWA0GWSbSKmPS1yaLHQoSV_4vg9PU_eFDFqsI_HtvYLX9zCh_7IaE-WDshhrbNoUfKcx0gSp1hwsOZIMEl08UmHz43ReGVh49N1ojL4kfZc1Rc2q67i4t01G1axJR_9EF_Q-ssLsOAYHwFJtGJaV9pcEWnK82zDsZLzrRluQPU0fjlYo6Wr91a5qQQPkxuxY_Qy3cZDnZa-jR__-6Q8DK_3XYkl9aJgqE-3gvshAFcEp9qgTSEgETq-7g_2rTE197khtVU0hjYRNI4aA
Cookie:refresh_token=Hd0-EMRLUj7CO-rrVvLgMaBJD33rTPpt5jXW0i1R86s; Max-Age=2592000; Expires=Fri, 15 May 2026 16:49:48 GMT;

### cambiar el estado de un listing
PATCH http://localhost:8080/api/listing/59e3ae4c-d3ab-4157-82f6-27cd6c0afbb3/status HTTP/1.1
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9VU0VSIl0sImF1dGhTdGF0dXMiOiJBQ1RJVkUiLCJpc3MiOiJCUjdGT1JMSUZFLmNvbSIsImV4cCI6MTc3NjQ4Nzc4OCwidXNlcklkIjoiYmJkMGZiYWYtMjMxOS00ZDM3LThkY2EtZWRmNDY4NDZiYWNiIiwiaWF0IjoxNzc2MjcxNzg4LCJqdGkiOiIxNjJhZmVlMC01Mjk4LTRlYzAtYTE4Mi1iMjBjZDQ1N2YxZjYifQ.Rz-RfAt8y5Viu2Pq1jQU9Y16o7jv6Zt22O-qpcEwBniKr3NuKI-StvjbBI5AE0GFtAN3YxuWA0GWSbSKmPS1yaLHQoSV_4vg9PU_eFDFqsI_HtvYLX9zCh_7IaE-WDshhrbNoUfKcx0gSp1hwsOZIMEl08UmHz43ReGVh49N1ojL4kfZc1Rc2q67i4t01G1axJR_9EF_Q-ssLsOAYHwFJtGJaV9pcEWnK82zDsZLzrRluQPU0fjlYo6Wr91a5qQQPkxuxY_Qy3cZDnZa-jR__-6Q8DK_3XYkl9aJgqE-3gvshAFcEp9qgTSEgETq-7g_2rTE197khtVU0hjYRNI4aA
Cookie:refresh_token=Hd0-EMRLUj7CO-rrVvLgMaBJD33rTPpt5jXW0i1R86s; Max-Age=2592000; Expires=Fri, 15 May 2026 16:49:48 GMT;
Content-Type: application/json 

{
  "publicationStatus": "ACTIVE"
}