### crear un listing

POST http://localhost:8080/api/listing HTTP/1.1
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJCUjdGT1JMSUZFLmNvbSIsInN1YiI6ImJyeWFuIiwiUk9MUyI6WyJST0xFX1VTRVIiXSwiZXhwIjoxNzczMTQ4MDk0LCJpYXQiOjE3NzI5MzIwOTQsImp0aSI6IjM5MzhkY2Q0LTVhZTctNGJlNy04YjMyLTJmMmU0MzViOTdiOCJ9.pu6YG_bXku7KviKvxHNoWjUX3MQobqeBw7Cxdj_ODCbx1yfHSD4TGjPh1ZkvgxSQXyPNibhmv6_K1duEWigML4BRZURFGSF_x3XSEFGR2BobaPPMjuJF7qq4j0WDw2yXHAonaVbHi0wCpnjIZrt6yYjI6xilcyNS3DVEgg0e0BWRhUOGgIlXBr1KTAREccZ8l6y6yz_uHTEsUHtEzKx5bxB7T9BF9JIKiPtSehwDuqUr1ZbCDQ5muSwTvGAD9PG0fN5g4i3lS1H5YQ_TDlhnj1SwXyTl2y2AZ0Qf6J1zTjgg6yO9Fgon60tjPdgqDI6HaIbkuC3ToFhQFxbPYvK2NA
Cookie:refresh_token=bPJKT9qrHTRkYpCr8fEHZM_x6zWLsc56lt7bXtvNWVU; Path=/api/auth; HttpOnly; Expires=Tue, 07 Apr 2026 01:08:14 GMT;
Content-Type: application/json


{
    "product": {
        "name": "iphone 14 pro max",
        "short_description": "iphone como nuevo",
        "long_description": "motivo de viaje",
        "model": "14 pro max",
        "sku": "123"
    },
    "price": 0.0,
    "currency": "USD"
}