### register product

POST http://localhost:8080/api/products/register HTTP/1.1
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9VU0VSIl0sImF1dGhTdGF0dXMiOiJBQ1RJVkUiLCJpc3MiOiJCUjdGT1JMSUZFLmNvbSIsImV4cCI6MTc3NTM1MDU3OSwidXNlcklkIjoiMTEyYTUxMjctZjEyMC00Yzc3LWJjMTgtY2I1Njc0NzdmYmRmIiwiaWF0IjoxNzc1MTM0NTc5LCJqdGkiOiIxNjUwMWI3NS1iMmJmLTQ4MTktYjRmNi0zYmM1ZGUxNTJiNjcifQ.y3APugF3_3UYpniaztfVlAFZK4Tn7VMiQROikhxeanTir8rPbHIDBM2etYQZVRP56yz8Cnp8xN6Ruo4XSQcEd_yaz3gHs5MYO84b3fcNpWSFCCXkB7lcYcD8sKR5ogGvAflRA7jrqLGjtvbZCC288m0qoTOkPz-nc_8lQNC3ZG6qwruqLS7TSz5e5v7JVYdZqgTu2boK9qitnljxqXxjeBIWmp_mC8Mj4YnkxzFzJktYtFrJJO3KIojVWpBp8dFCyIBiOIhgu2BDgpK3Sdqn1BrE517tohCyqKg675cVtN6Wjn46v0tUV0bmw9yYiYz8owmbjkeycQqI8l8s2eKbMA
Cookie:refresh_token=NiIOu99DFtN0f1ySAhj3481VneYoIh91wjaO50QBYr0; Max-Age=2592000; Expires=Sat, 02 May 2026 12:56:20 GMT;  
Content-Type: application/json

{
    "name": "iphone 14",
    "sku": "456789",
    "shortDescription": "Telefono iphone 14 pro max",
    "longDescription": null,
    "model": "14"
}