### obtener los producto por su id

GET http://localhost:8080/api/products/ae52786d-6f38-4b4e-b206-0959fa7c2995 HTTP/1.1
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9VU0VSIl0sImF1dGhTdGF0dXMiOiJBQ1RJVkUiLCJpc3MiOiJCUjdGT1JMSUZFLmNvbSIsImV4cCI6MTc3NjA2NTYzMSwidXNlcklkIjoiMTEyYTUxMjctZjEyMC00Yzc3LWJjMTgtY2I1Njc0NzdmYmRmIiwiaWF0IjoxNzc1ODQ5NjMxLCJqdGkiOiIxMjllZWI3MS1hN2M2LTQ5ZjYtOWNlNS1mOWYxY2FlYWM0NDQifQ.W0zYIjZgUQhYjrLNRPY_vhCpb6TITMgXExtCQ-OlECt9rAdsGX0_eQxgC1uv3Gi8D_ikSHQrk3w2LaMcgOVCKjVEi9datm84BaPV5LgxS1fBDR7au_q1Wym21_bVYILcMZNDIPt_wrtEfv87sjcKqwacly3KzNT72pcSSToFwv68CLVrT39mGi1ZPSII29IwjBYUXs37eFs5umnBWZEbs4qCOPjFi2OeexvUk-Xxcb4xK-fjcHR4GYNKYJts-12ma10gTX4A7fTi0c6n4MdM9XniLYFGmbeOPH03ujRCQsT_qt5uEj673vnW9gEApWlmBjV8n8i0cIWS3l2TIo5OBA
Cookie:refresh_token=QTahOp6adle5U7WPB4WPbcPLMlKRSOxbT8hYbIW1Tlo; Max-Age=2592000; Expires=Sun, 10 May 2026 19:33:51 GMT;

### obtener todos los productos dependiendo si es un cliente o es un
### administrador
GET http://localhost:8080/api/products  HTTP/1.1
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9VU0VSIl0sImF1dGhTdGF0dXMiOiJBQ1RJVkUiLCJpc3MiOiJCUjdGT1JMSUZFLmNvbSIsImV4cCI6MTc3NjA2NTYzMSwidXNlcklkIjoiMTEyYTUxMjctZjEyMC00Yzc3LWJjMTgtY2I1Njc0NzdmYmRmIiwiaWF0IjoxNzc1ODQ5NjMxLCJqdGkiOiIxMjllZWI3MS1hN2M2LTQ5ZjYtOWNlNS1mOWYxY2FlYWM0NDQifQ.W0zYIjZgUQhYjrLNRPY_vhCpb6TITMgXExtCQ-OlECt9rAdsGX0_eQxgC1uv3Gi8D_ikSHQrk3w2LaMcgOVCKjVEi9datm84BaPV5LgxS1fBDR7au_q1Wym21_bVYILcMZNDIPt_wrtEfv87sjcKqwacly3KzNT72pcSSToFwv68CLVrT39mGi1ZPSII29IwjBYUXs37eFs5umnBWZEbs4qCOPjFi2OeexvUk-Xxcb4xK-fjcHR4GYNKYJts-12ma10gTX4A7fTi0c6n4MdM9XniLYFGmbeOPH03ujRCQsT_qt5uEj673vnW9gEApWlmBjV8n8i0cIWS3l2TIo5OBA
Cookie:refresh_token=QTahOp6adle5U7WPB4WPbcPLMlKRSOxbT8hYbIW1Tlo; Max-Age=2592000; Expires=Sun, 10 May 2026 19:33:51 GMT;  