### obtener los producto por su id
GET http://localhost:8080/api/products/ae52786d-6f38-4b4e-b206-0959fa7c2995 HTTP/1.1
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9VU0VSIl0sImF1dGhTdGF0dXMiOiJBQ1RJVkUiLCJpc3MiOiJCUjdGT1JMSUZFLmNvbSIsImV4cCI6MTc3NjQ4Nzc4OCwidXNlcklkIjoiYmJkMGZiYWYtMjMxOS00ZDM3LThkY2EtZWRmNDY4NDZiYWNiIiwiaWF0IjoxNzc2MjcxNzg4LCJqdGkiOiIxNjJhZmVlMC01Mjk4LTRlYzAtYTE4Mi1iMjBjZDQ1N2YxZjYifQ.Rz-RfAt8y5Viu2Pq1jQU9Y16o7jv6Zt22O-qpcEwBniKr3NuKI-StvjbBI5AE0GFtAN3YxuWA0GWSbSKmPS1yaLHQoSV_4vg9PU_eFDFqsI_HtvYLX9zCh_7IaE-WDshhrbNoUfKcx0gSp1hwsOZIMEl08UmHz43ReGVh49N1ojL4kfZc1Rc2q67i4t01G1axJR_9EF_Q-ssLsOAYHwFJtGJaV9pcEWnK82zDsZLzrRluQPU0fjlYo6Wr91a5qQQPkxuxY_Qy3cZDnZa-jR__-6Q8DK_3XYkl9aJgqE-3gvshAFcEp9qgTSEgETq-7g_2rTE197khtVU0hjYRNI4aA
Cookie:refresh_token=Hd0-EMRLUj7CO-rrVvLgMaBJD33rTPpt5jXW0i1R86s; Max-Age=2592000; Expires=Fri, 15 May 2026 16:49:48 GMT;

### obtener todos los productos dependiendo si es un cliente o es un
### administrador
GET http://localhost:8080/api/products  HTTP/1.1
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJicnlhbiIsIlJPTFMiOlsiUk9MRV9VU0VSIl0sImF1dGhTdGF0dXMiOiJBQ1RJVkUiLCJpc3MiOiJCUjdGT1JMSUZFLmNvbSIsImV4cCI6MTc3NjQ4Nzc4OCwidXNlcklkIjoiYmJkMGZiYWYtMjMxOS00ZDM3LThkY2EtZWRmNDY4NDZiYWNiIiwiaWF0IjoxNzc2MjcxNzg4LCJqdGkiOiIxNjJhZmVlMC01Mjk4LTRlYzAtYTE4Mi1iMjBjZDQ1N2YxZjYifQ.Rz-RfAt8y5Viu2Pq1jQU9Y16o7jv6Zt22O-qpcEwBniKr3NuKI-StvjbBI5AE0GFtAN3YxuWA0GWSbSKmPS1yaLHQoSV_4vg9PU_eFDFqsI_HtvYLX9zCh_7IaE-WDshhrbNoUfKcx0gSp1hwsOZIMEl08UmHz43ReGVh49N1ojL4kfZc1Rc2q67i4t01G1axJR_9EF_Q-ssLsOAYHwFJtGJaV9pcEWnK82zDsZLzrRluQPU0fjlYo6Wr91a5qQQPkxuxY_Qy3cZDnZa-jR__-6Q8DK_3XYkl9aJgqE-3gvshAFcEp9qgTSEgETq-7g_2rTE197khtVU0hjYRNI4aA
Cookie:refresh_token=Hd0-EMRLUj7CO-rrVvLgMaBJD33rTPpt5jXW0i1R86s; Max-Age=2592000; Expires=Fri, 15 May 2026 16:49:48 GMT;